### ISSUE TITLE
Download .loc files

### ISSUE THREAD

**Issue by codecat** [ManiaCDN/uploader#19]
Add a way to automatically download a zip full of .loc files for a folder or for your entire user folder. This is very helpful if you have a folder with a lot of files, and don't want to make .loc files for every single one manually.

**Comment by askuri** [comment]
Great idea, thanks! I'll take a look at this.

**Comment by askuri** [comment]
Pushed it to the server. You find the button in the navigation bar above the file listing. Let me know if this is what you were looking for or if anything is missing.

Feel free to close the issue if everything is okay.

**Comment by codecat** [comment]
Perfect, thank you! 🎉 

I was assuming it would be more like "download loc files for the current folder and subfolders" rather than "download loc files for everything" but I guess the files are small enough that this works either way. 👍

**Comment by askuri** [comment]
It actually creates the .loc files only for the current folder and its subfolders. Though, you still see the folder structure above. Maybe that is more confusing than I thought it would be.

Still you're right, the files are very small. Even generating the .loc files for all users happens almost instantly.

**Comment by codecat** [comment]
Ahh, I see. Might be better without all of the subdirectories then!
